name: clan_manager_app
description: Aplicativo de gerenciamento de clã com interface inspirada no Discord.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.0
  path_provider: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
